### PR TITLE
Empty stylesheet improvements

### LINKED ISSUE #134: Writing default stylesheet to file results in excel complaining it's invalid
this relates to the existence of `minimalStylesheet` and `def` for `Stylesheet`. using `def` will result in a file that cannot load.

This is also easily hit if for some reason you wrote out a file using `xlsx` and did not specify a stylesheet, an 'empty' stylesheet will be added. if you end up parsing that stylesheet and writing it back out it will be invalid also.

this seems to be because `dxfs` will not work unless the minimal fonts are specified as with the other stuff in stylesheet. removing `dxfs` lets excel load the file again.

### PR DESCRIPTION
**Pull request by qrilka**
Resolves #134

### CODE REVIEW

**Comment by qrilka** [comment]
@dten I've invited you to become a collaborator on this project (otherwise I can't assign you to review this :) )

**Comment by qrilka** [comment]
@dten do you have a minute to take a look into this?

**Comment by dten** [comment]
I will this evening sorry

**Comment by qrilka** [comment]
There's no particular rush but will you have a moment for it in one of upcoming days?

**Comment by qrilka** [comment]
Hi @dten 
I guess you don't have time for this thus I'll merge this tomorrow even if there will be no feedback from you.

**Comment by dten** [comment]
Really sorry! Just been busy with work. I'll really really try have a look tonight

**Comment by dten** [comment]
😅 was just testing this and it does fix the problem i was getting. the below now produces a file Excel will open wheras before it would not

```
{-# LANGUAGE OverloadedStrings #-}

module Main where

import Codec.Xlsx
import Control.Lens
import qualified Data.ByteString.Lazy as L
import Data.Time.Clock.POSIX

main :: IO ()
main = do
  ct <- getPOSIXTime
  let
      sheet = def & cellValueAt (1,2) ?~ CellDouble 42.0
                  & cellValueAt (3,2) ?~ CellText "foo"
      xlsx = def & (atSheet "List1" ?~ sheet)
                 & (xlStyles .~ renderStyleSheet def)
  L.writeFile "example.xlsx" $ fromXlsx ct xlsx
```

**Pull request merged**
