### PR TITLE
Add hidden property to rows

### PR DESCRIPTION
**Pull request by Shimuuar**
No real tests. Would be grateful if you say how they should be added

### CODE REVIEW

**Comment by qrilka** [comment]
Thanks a lot, I don't think there is real need for special tests for this

**Comment by qrilka** [comment]
Actually I see a minor bug of mine in that code :)

**Comment by Shimuuar** [comment]
You mean calculation of hasHeight flag? (:

**Comment by qrilka** [comment]
Yeah, `customHeight`, fixed in 1130835dd66537d3e16dba4a95137dcbb48e1045

**Pull request merged**
