### PR TITLE
Fix #122

### LINKED ISSUE #122: Richtext cell: single underlining in sharedstrings not recognized
Hi

If I have a simple xlsx file with just one cell containing a single and double underline then only the double underline is recognized.
In case of a more complex xlsx file, things get structured differently and there it seems to behave correctly.

An example:

excel:
*A1*
```
Single | Double underline
------   =====
```

sharedstrings.xml

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<sst xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" count="1" uniqueCount="1">
  <si>
    <r>
      <rPr>
        <u/>
...
      </rPr>
      <t>Single</t>
    </r>
...
    <r>
      <rPr>
        <u val="double"/>
...
      </rPr>
      <t>Double</t>
    </r>
...
  </si>
</sst>
```

Note: I haven't checked the specs as to whether my version of excel actually wrongfully encodes `<u />` instead of `<u val="single" />`

### PR DESCRIPTION
**Pull request by dvekeman**
Richtext cell: underlining not recognized

### CODE REVIEW

**Comment by qrilka** [comment]
Thanks @dvekeman it looks like you're completely right, according to the spec:
```
<xsd:complexType name="CT_UnderlineProperty">
<xsd:attribute name="val" type="ST_UnderlineValues" use="optional" default="single"/>
</xsd:complexType>
```
What do you think about adding `justNonDef` to get the same `<u/>` in output for single underline?
Otherwise looks to be a perfect fix for the problem.

**Comment by dvekeman** [comment]
Hi
Thanks for the feedback!
I'm not sure if I got it right, but I submitted a second commit where I use the `justNonDef` when creating the Element to get back an `<u/>` tag without attributes instead of `<u val="single"/>`

**Comment by qrilka** [comment]
Great, I will try to refactor it a bit (e.g. `attrValues` is a misleading name as it produces only 1 "value") and will merge

**Comment by dvekeman** [comment]
Awesome, thanks again!

**Pull request merged**
