### PR TITLE
Update defaults

### PR DESCRIPTION
**Pull request by vesten**
Adding some defaults values I found in the spec to various Default instances in StyleSheet.hs. Reference issue #54.

### CODE REVIEW

**Comment by qrilka** [comment]
Actually now I understand that I didn't get your point correctly yesterday - you are setting default values for the record types but spec says about setting defaults while reading **existing** elements (though for attributes like `_colorTint` there is no element so those values could be set in `def`).
So the point is to treat `<b/>` the same way like `<b val="true"/>` but that doesn't mean that every `Font` will be bold out of the box. 
And setting `True` for properties `_cellXfApplyXXX` without setting `_cellXfXXX` at the same time should even result in inconsistent data.
So please revise the PR.
BTW your fork seems to have diverged somewhat from `master` - could you rebase your work next time and also fix tests in your branch? Thanks

**Comment by qrilka** [comment]
Hi @vesten - any updates on this? Or maybe I should just close it?

**Comment by vesten** [comment]
Hi @qrilka, I've been away for the Independence Holiday. I'll try to spend some time tomorrow night and clean this up.

**Comment by vesten** [comment]
OK. Looking at it a bit more I think I finally understand that attribute default values apply when the attribute is present NOT when they are absent (as a substitute value). Amazing how things are clearer after a little vacation.  :)  Thanks for your comments as well.  Given this, I no longer think a change is warranted and issues #54 and #55 can be closed if you agree also.

**Pull request closed without merging**
