### PR TITLE
fix typo + colorToARGB

### PR DESCRIPTION
**Pull request by stla**
- Fixed a typo: `NfTousands2DecimalNEgativeRed` -> `NfThousands2DecimalNegativeRed`

- Added helper function `colorToARGB`, which maps a color name among 657 color names (the ones known by R) to its ARGB value (without opacity, i.e. A=FF).

If this can help...

### CODE REVIEW

**Comment by qrilka** [comment]
Hello @stla 
Somehow I missed notification about this PR, sorry.
Thanks for fixing that misprint.
As for the colors - what are those names? Something from CSS? Then something like `cssColorToARGB` would be a bit more descriptive and also it looks somewhat out of scope for this library (also it would be more typesafe to have those colors as identifiers and not just a `Text` so that function could be made total)

**Comment by stla** [comment]
Hi @qrilka 
These are the 657 built in colors in R. Indeed, the names are similar to the CSS color names, but according to [W3schools](https://www.w3schools.com/cssref/css_colors.asp), there are only 140 usual CSS color names. I generated this Haskell code from R, of course I didn't type it manually.
By "colors as identifiers", you mean defining a data constructor ? Like `data cssColor = aliceblue | antiquewhite | ...` ?

**Comment by qrilka** [comment]
in Haskell that would be `data CssColor = Aliceblue | Antiquewhite | ... ` :)
Or in `clay` it's `aliceblue :: Color` - http://hackage.haskell.org/package/clay-0.12.2/docs/Clay-Color.html#v:aliceblue
As for R-related things, probably HaskellR is more proper place for it?

**Comment by stla** [comment]
No problem. I understand it's out of the scope of `xlsx`. 
Originally I did that for my executable [json2xlsx](https://github.com/stla/json2xlsx/blob/master/src/JSONtoXLSX/JSONtoCellMap/ColorsRGB.hs) (based on `xlsx`). It was cost free to share.

**Comment by qrilka** [comment]
@stla are you OK with merging only 57c9e610812b1c8cde964b75ef5ca0136b5a007f ?

**Comment by stla** [comment]
@qrilka Yes, sure.

**Comment by qrilka** [comment]
thanks @stla

**Pull request closed without merging**
