### PR TITLE
Extract "Format" and "NumberFormat" to a separate file

### PR DESCRIPTION
**Pull request by Anarchist666**

### CODE REVIEW

**Comment by qrilka** [comment]
And what's the point? Have you seen build errors?

**Comment by Anarchist666** [comment]
> And what's the point?

I want to add a high-level type "NamedStyle". And i'm going to move all hi-level types, such as "Format", "NumberFormat", "NamedStyle" into a separate file.

>Have you seen build errors?

It was tested with ghc 8.2 and 8.4 without any errors.

**Comment by qrilka** [comment]
I have only 1 point about this refactoring - it appears that it's more logical to have `StyleSheet` as a part of `Styles`, as a submodule or even as a part of it. Having both `Styles` and `StyleSheet` at the same time looks confusing.

**Comment by Anarchist666** [comment]
> or even as a part of it.

Ok. It'll be great.

**Comment by qrilka** [comment]
@Anarchist666 are you still working on this?

**Comment by qrilka** [comment]
@Anarchist666 please raise your voice if you're against closing this one, we could reopen this then

**Pull request closed without merging**
