### PR TITLE
Relax lens upper bound

### PR DESCRIPTION
**Pull request by parsonsmatt**

### CODE REVIEW

**Comment by qrilka** [comment]
Thanks

**Comment by parsonsmatt** [comment]
thank you!

any chance we could get a Hackage revision?

**Comment by qrilka** [comment]
Hi, I had a thought about that - will try to find some time for that soon, thanks for asking

**Comment by qrilka** [comment]
@parsonsmatt 1.1.0 is on Hackage

**Comment by parsonsmatt** [comment]
Thank you!

**Pull request merged**
